spring.application.name=cv-generator

openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.api.model=meta-llama/llama-3.3-70b-instruct:free
#openrouter.api.model=anthropic/claude-3.5-haiku
#openrouter.api.model=fake/model-that-doesnt-exist